#!/usr/bin/env python3
"""Generate a FERRITE_PLATFORM_MANIFEST for Windows builds.

Probes the host for:
  - CUDA Toolkit location (CUDA_PATH, common install dirs)
  - MSVC toolchain (cl.exe via vswhere)
  - GPU compute capability (nvidia-smi)

Writes ``ferrite_platform_manifest.toml`` in the current directory.
"""

import os
import sys
import subprocess
import shutil
from pathlib import Path

MANIFEST_NAME = "ferrite_platform_manifest.toml"


def find_cuda() -> str | None:
    """Locate the CUDA Toolkit root directory."""
    for var in ("CUDA_PATH", "CUDA_HOME", "CUDA_ROOT"):
        val = os.environ.get(var)
        if val and Path(val, "include", "cuda_runtime.h").exists():
            return val

    # Common Windows install locations
    prog = os.environ.get("ProgramFiles", r"C:\Program Files")
    base = Path(prog, "NVIDIA GPU Computing Toolkit", "CUDA")
    if base.exists():
        versions = sorted(base.iterdir(), reverse=True)
        for v in versions:
            if (v / "include" / "cuda_runtime.h").exists():
                return str(v)

    # Try nvcc on PATH
    nvcc = shutil.which("nvcc")
    if nvcc:
        cuda = Path(nvcc).resolve().parent.parent
        if (cuda / "include" / "cuda_runtime.h").exists():
            return str(cuda)

    return None


def detect_gpu_sm() -> str | None:
    """Detect GPU compute capability via nvidia-smi."""
    for query in ("compute_cap", "compute_capability"):
        try:
            out = subprocess.check_output(
                ["nvidia-smi", f"--query-gpu={query}", "--format=csv,noheader"],
                text=True, timeout=10
            ).strip()
            if out:
                digits = "".join(c for c in out.split("\n")[0] if c.isdigit())
                if digits:
                    return f"sm_{digits}"
        except (FileNotFoundError, subprocess.SubprocessError):
            pass
    return None


def find_ferrite_lib(repo_root: Path) -> str | None:
    """Locate the pre-built ferrite lib directory."""
    for candidate in (repo_root / "ferrite-os" / "lib", repo_root / "lib"):
        if candidate.exists():
            return str(candidate)
    return None


def main():
    repo_root = Path(__file__).resolve().parent.parent.parent

    cuda_path = find_cuda()
    gpu_sm = detect_gpu_sm() or "sm_75"
    ferrite_lib = find_ferrite_lib(repo_root)

    lines = []
    lines.append("# Auto-generated by scripts/windows_builder/generate_manifest.py")
    lines.append(f"# Generated on: {os.name}")
    lines.append("")

    # ── [ptx-sys] ────────────────────────────────────────────────
    lines.append("[ptx-sys]")

    lib_dirs = []
    if cuda_path:
        cuda_lib = Path(cuda_path, "lib", "x64")
        if not cuda_lib.exists():
            cuda_lib = Path(cuda_path, "lib64")
        if not cuda_lib.exists():
            cuda_lib = Path(cuda_path, "lib")
        lib_dirs.append(str(cuda_lib))
    if ferrite_lib:
        lib_dirs.append(ferrite_lib)

    lines.append(f'lib_dirs = [{", ".join(f\'"{d}"\' for d in lib_dirs)}]')
    lines.append('link_libs = ["ptx_os", "cudart", "cublas"]')
    lines.append('link_kind = "dylib"')

    if cuda_path:
        lines.append(f'include_dirs = ["{Path(cuda_path, "include")}"]')

    lines.append(f'gpu_sm = "{gpu_sm}"')
    lines.append("")

    # ── [ptx-kernels] ────────────────────────────────────────────
    lines.append("[ptx-kernels]")

    if cuda_path:
        lines.append(f'cuda_path = "{cuda_path}"')
        lines.append(f'cuda_arch = "{gpu_sm}"')
        kernel_lib_dirs = [str(Path(cuda_path, "lib", "x64"))]
        lines.append(f'lib_dirs = [{", ".join(f\'"{d}"\' for d in kernel_lib_dirs)}]')
        lines.append('link_libs = ["cudart", "cuda"]')
        lines.append("skip_kernel_build = false")
    else:
        lines.append("# CUDA not found — kernel build will be skipped.")
        lines.append("# Provide pre-built kernel libraries via lib_dirs if needed.")
        lines.append("skip_kernel_build = true")
        lines.append("lib_dirs = []")
        lines.append("link_libs = []")

    lines.append("")

    manifest = "\n".join(lines)

    out_path = Path(MANIFEST_NAME)
    out_path.write_text(manifest, encoding="utf-8")
    print(f"Wrote {out_path.resolve()}")
    print()
    print(manifest)

    if not cuda_path:
        print("WARNING: CUDA Toolkit not found. GPU kernel compilation will be skipped.", file=sys.stderr)

    return 0


if __name__ == "__main__":
    sys.exit(main())
