//! Raw FFI bindings to PTX-OS GPU runtime and CUDA libraries.
//!
//! This crate provides unsafe bindings generated by bindgen from the PTX-OS headers.
//! For safe wrappers, use the `ptx-runtime` crate.
//!
//! # Safety
//!
//! All functions in this crate are unsafe. The caller must ensure:
//! - Valid pointers are passed
//! - Proper synchronization for concurrent access
//! - Memory is properly allocated via PTX-OS allocator

#![allow(non_upper_case_globals)]
#![allow(non_camel_case_types)]
#![allow(non_snake_case)]
#![allow(dead_code)]
#![allow(clippy::all)]

use libc::{c_char, c_int, c_uint, c_void, size_t, ssize_t};

// CUDA types as opaque pointers
pub type cudaStream_t = *mut c_void;
pub type cudaGraph_t = *mut c_void;
pub type cudaGraphExec_t = *mut c_void;
pub type cudaError_t = c_int;
pub type cudaGraphicsResource_t = *mut c_void;

// CUDA driver API context handle
pub type CUcontext = *mut c_void;

// dim3 struct for kernel launch configuration
#[repr(C)]
#[derive(Debug, Copy, Clone, Default)]
pub struct dim3 {
    pub x: u32,
    pub y: u32,
    pub z: u32,
}

impl dim3 {
    pub fn new(x: u32, y: u32, z: u32) -> Self {
        Self { x, y, z }
    }
}

// CUDA IPC memory handle
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct cudaIpcMemHandle_t {
    pub reserved: [c_char; 64],
}

impl Default for cudaIpcMemHandle_t {
    fn default() -> Self {
        Self { reserved: [0; 64] }
    }
}

// Half precision type placeholder
#[repr(C)]
#[derive(Debug, Copy, Clone, Default)]
pub struct __half {
    pub x: u16,
}

// Type aliases for convenience
pub type DType = PTXDType;
pub type OpCode = PTXTensorOpcode;

// ============================================================================
// Configuration Constants
// ============================================================================

pub const GPU_HOT_MAX_STREAMS: u32 = 100000;  // UNLIMITED! Can run tens of thousands of streams!
pub const GPU_HOT_MAX_KERNELS: u32 = 256;
pub const GPU_HOT_MAX_GRAPHS: u32 = 256;      // Increased for graph pooling
pub const GPU_HOT_MAX_NAMED_SEGMENTS: u32 = 256;
pub const GPU_HOT_MAX_NAME_LEN: u32 = 64;
pub const GPU_HOT_DEFAULT_VRAM_PERCENT: f32 = 70.0;
pub const PTX_STABLE_ABI_VERSION: u32 = 1;
pub const PTX_STABLE_CONFIG_DEFAULT: u32 = 0;
pub const PTX_STABLE_CONFIG_PREFER_ORIN_UM: u32 = 1 << 0;
pub const PTX_STABLE_CONFIG_USE_MANAGED_POOL: u32 = 1 << 1;
pub const PTX_STABLE_INVALID_DEVICE: i32 = -1;

pub const TLSF_FL_INDEX_MAX: u32 = 32;
pub const TLSF_SL_INDEX_COUNT: u32 = 16;
pub const TLSF_MIN_BLOCK_SIZE: u32 = 64;
pub const TLSF_ALIGNMENT: u32 = 256;

pub const PTX_MAX_QUEUE_SIZE: u32 = 1024;
pub const PTX_MAX_TASK_ARGS: u32 = 8;

pub const PTX_PRIORITY_REALTIME: u32 = 0;
pub const PTX_PRIORITY_HIGH: u32 = 1;
pub const PTX_PRIORITY_NORMAL: u32 = 2;
pub const PTX_PRIORITY_LOW: u32 = 3;

pub const VMM_PAGE_SIZE: u32 = 64 * 1024;
pub const VMM_MAX_PAGES: u32 = 16384;
pub const VMM_MAX_SWAP_REGIONS: u32 = 256;

pub const VFS_MAX_NODES: u32 = 1024;
pub const VFS_MAX_PATH_LEN: u32 = 256;
pub const VFS_MAX_OPEN_FILES: u32 = 256;

// VMM Flags
pub const VMM_FLAG_READ: u32 = 0x01;
pub const VMM_FLAG_WRITE: u32 = 0x02;
pub const VMM_FLAG_EXEC: u32 = 0x04;
pub const VMM_FLAG_SHARED: u32 = 0x08;
pub const VMM_FLAG_PINNED: u32 = 0x10;

// VFS Open Flags
pub const VFS_O_RDONLY: u32 = 0x01;
pub const VFS_O_WRONLY: u32 = 0x02;
pub const VFS_O_RDWR: u32 = 0x03;
pub const VFS_O_CREAT: u32 = 0x10;
pub const VFS_O_TRUNC: u32 = 0x20;
pub const VFS_O_APPEND: u32 = 0x40;

// ============================================================================
// Tensor Opcodes
// ============================================================================

#[repr(u32)]
#[derive(Debug, Copy, Clone, PartialEq, Eq, Hash, Default)]
pub enum PTXTensorOpcode {
    // Binary Operations (0x10 - 0x1F)
    #[default]
    Add = 0x10,
    Sub = 0x11,
    Mul = 0x12,
    Div = 0x13,
    Max = 0x14,
    Min = 0x15,
    Pow = 0x16,
    Mod = 0x17,

    // Unary Operations (0x20 - 0x3F)
    Neg = 0x20,
    Abs = 0x21,
    Exp = 0x22,
    Log = 0x23,
    Log2 = 0x24,
    Log10 = 0x25,
    Sqrt = 0x26,
    Rsqrt = 0x27,
    Sin = 0x28,
    Cos = 0x29,
    Tan = 0x2A,
    Tanh = 0x2B,
    Sinh = 0x2C,
    Cosh = 0x2D,
    Ceil = 0x2E,
    Floor = 0x2F,
    Round = 0x30,
    Sign = 0x31,
    Recip = 0x32,
    Sqr = 0x33,
    Erf = 0x34,

    // Activation Functions (0x40 - 0x4F)
    Relu = 0x40,
    Relu6 = 0x41,
    LeakyRelu = 0x42,
    Elu = 0x43,
    Selu = 0x44,
    Gelu = 0x45,
    GeluTanh = 0x46,
    Sigmoid = 0x47,
    Silu = 0x48,
    Softplus = 0x49,
    Mish = 0x4A,
    HardSwish = 0x4B,
    HardSigmoid = 0x4C,

    // Reduction Operations (0x50 - 0x5F)
    ReduceSum = 0x50,
    ReduceMean = 0x51,
    ReduceMax = 0x52,
    ReduceMin = 0x53,
    ReduceProd = 0x54,
    ReduceArgmax = 0x55,
    ReduceArgmin = 0x56,

    // Softmax Operations (0x60 - 0x6F)
    Softmax = 0x60,
    LogSoftmax = 0x61,

    // Comparison Operations (0x70 - 0x7F)
    CmpEq = 0x70,
    CmpNe = 0x71,
    CmpLt = 0x72,
    CmpLe = 0x73,
    CmpGt = 0x74,
    CmpGe = 0x75,

    // Affine/Transform Operations (0x80 - 0x8F)
    Affine = 0x80,
    Clamp = 0x81,
    Where = 0x82,

    // Copy Operations (0x90 - 0x9F)
    Copy = 0x90,
    Cast = 0x91,
    Fill = 0x92,

    // Gather/Scatter Operations (0xB0 - 0xB5)
    Gather = 0xB0,
    ScatterAdd = 0xB1,
    IndexSelect = 0xB2,
    IndexAdd = 0xB3,

    // Scan/Prefix Operations (0xC0 - 0xC5)
    CumSum = 0xC0,

    // Sort/Select Operations (0xE0 - 0xEF)
    Argsort = 0xE1,
    TopK = 0xE2,
}

// ============================================================================
// Data Types
// ============================================================================

#[repr(u32)]
#[derive(Debug, Copy, Clone, PartialEq, Eq, Hash, Default)]
pub enum PTXDType {
    #[default]
    F32 = 0,
    F64 = 1,
    F16 = 2,
    BF16 = 3,
    I8 = 4,
    I16 = 5,
    I32 = 6,
    I64 = 7,
    U8 = 8,
    U32 = 9,
}

impl PTXDType {
    /// Size in bytes
    pub const fn size_bytes(&self) -> usize {
        match self {
            PTXDType::F32 => 4,
            PTXDType::F64 => 8,
            PTXDType::F16 => 2,
            PTXDType::BF16 => 2,
            PTXDType::I8 => 1,
            PTXDType::I16 => 2,
            PTXDType::I32 => 4,
            PTXDType::I64 => 8,
            PTXDType::U8 => 1,
            PTXDType::U32 => 4,
        }
    }
}

// ============================================================================
// VFS Node Type
// ============================================================================

#[repr(u32)]
#[derive(Debug, Copy, Clone, PartialEq, Eq)]
pub enum VFSNodeType {
    File = 0,
    Directory = 1,
    Tensor = 2,
    Stream = 3,
    Device = 4,
}

// ============================================================================
// Opaque Runtime Pointer
// ============================================================================

#[repr(C)]
pub struct GPUHotRuntime {
    _private: [u8; 0],
}

#[repr(C)]
pub struct PTXTLSFAllocator {
    _private: [u8; 0],
}

#[repr(C)]
pub struct PTXStableRuntime {
    _private: [u8; 0],
}

#[repr(i32)]
#[derive(Debug, Copy, Clone, PartialEq, Eq)]
pub enum PTXStableStatus {
    Ok = 0,
    ErrInvalidArg = 1,
    ErrAbiMismatch = 2,
    ErrInitFailed = 3,
    ErrNotInitialized = 4,
    ErrNotOwned = 5,
    ErrAllocFailed = 6,
    ErrInternal = 7,
}

#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct PTXStableConfig {
    pub struct_size: u32,
    pub abi_version: u32,
    pub flags: u32,
    pub device_id: i32,
    pub pool_fraction: f32,
    pub fixed_pool_size: u64,
    pub reserve_vram: u64,
    pub max_streams: u32,
    pub quiet_init: u8,
    pub enable_leak_detection: u8,
    pub enable_pool_health: u8,
    pub _reserved0: u8,
}

impl Default for PTXStableConfig {
    fn default() -> Self {
        Self {
            struct_size: std::mem::size_of::<PTXStableConfig>() as u32,
            abi_version: PTX_STABLE_ABI_VERSION,
            flags: PTX_STABLE_CONFIG_DEFAULT,
            device_id: PTX_STABLE_INVALID_DEVICE,
            pool_fraction: 0.0,
            fixed_pool_size: 0,
            reserve_vram: 0,
            max_streams: 0,
            quiet_init: 0,
            enable_leak_detection: 1,
            enable_pool_health: 1,
            _reserved0: 0,
        }
    }
}

#[repr(C)]
#[derive(Debug, Copy, Clone, Default)]
pub struct PTXStableStats {
    pub vram_allocated: u64,
    pub vram_used: u64,
    pub vram_free: u64,
    pub gpu_utilization: f32,
    pub pool_total: u64,
    pub pool_used: u64,
    pub pool_free: u64,
    pub pool_peak: u64,
    pub pool_fallbacks: u64,
    pub pool_fragmentation: f32,
    pub total_ops: u64,
    pub active_streams: u32,
    pub refcount: u32,
    pub watchdog_tripped: u8,
    pub _reserved: [u8; 3],
}

// ============================================================================
// Structures
// ============================================================================

#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct TLSFBlock {
    pub device_ptr: *mut c_void,
    pub size: size_t,
    pub magic: u32,
    pub prev_phys: *mut TLSFBlock,
    pub next_phys: *mut TLSFBlock,
    pub prev_free: *mut TLSFBlock,
    pub next_free: *mut TLSFBlock,
    pub hash_next: *mut TLSFBlock,
    pub is_free: bool,
    pub is_last: bool,
    pub is_pinned: bool,
    pub alloc_id: u32,
    pub alloc_file: *const c_char,
    pub alloc_line: c_int,
    pub alloc_timestamp: u64,
    pub owner_id: u32,
}

#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct GPUGraphHandle {
    pub name: [c_char; 64],
    pub graph: cudaGraph_t,
    pub graph_exec: cudaGraphExec_t,
    pub is_valid: bool,
}

#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct GPUKernelHandle {
    pub kernel_func: *mut c_void,
    pub grid: dim3,
    pub block: dim3,
    pub shared_mem: size_t,
    pub stream: cudaStream_t,
}

#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct GPURegistryEntry {
    pub name: [c_char; 64],
    pub ipc_handle: cudaIpcMemHandle_t,
    pub size: size_t,
    pub active: bool,
    pub created_at: u64,
    pub ref_count: u32,
    pub owner_pid: u32,
}

#[repr(C)]
#[derive(Debug, Copy, Clone, Default)]
pub struct PTXOSTask {
    pub task_id: u32,
    pub opcode: u32,
    pub priority: u32,
    pub active: bool,
    pub completed: bool,
    pub args: [*mut c_void; 8],
    pub submitted_at: u64,
    pub completed_at: u64,
}

#[repr(C)]
#[derive(Debug)]
pub struct PTXTaskQueue {
    pub tasks: [PTXOSTask; 1024],
    pub head: u32,
    pub tail: u32,
    pub lock: u32,
}

#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct VMMPageEntry {
    pub gpu_addr: *mut c_void,
    pub original_addr: *mut c_void,
    pub host_addr: *mut c_void,
    pub size: size_t,
    pub flags: u32,
    pub last_access: u64,
    pub access_count: u32,
    pub resident: bool,
    pub dirty: bool,
    pub pinned: bool,
}

#[repr(C)]
pub struct VMMState {
    pub runtime: *mut GPUHotRuntime,
    pub pages: [VMMPageEntry; 16384],
    pub num_pages: u32,
    pub resident_pages: u32,
    pub swapped_pages: u32,
    pub swap_regions: [*mut c_void; 256],
    pub swap_region_sizes: [size_t; 256],
    pub num_swap_regions: u32,
    pub total_swap_size: size_t,
    pub used_swap_size: size_t,
    pub page_faults: u64,
    pub swap_ins: u64,
    pub swap_outs: u64,
    pub evictions: u64,
}

#[repr(C)]
#[derive(Debug)]
pub struct VFSInode {
    pub inode_id: u32,
    pub name: [c_char; 64],
    pub path: [c_char; 256],
    pub node_type: VFSNodeType,
    pub data: *mut c_void,
    pub size: size_t,
    pub dims: c_int,
    pub shape: [c_int; 8],
    pub dtype: c_int,
    pub parent: *mut VFSInode,
    pub first_child: *mut VFSInode,
    pub next_sibling: *mut VFSInode,
    pub created_at: u64,
    pub modified_at: u64,
    pub accessed_at: u64,
    pub mode: u32,
    pub uid: u32,
    pub gid: u32,
    pub active: bool,
}

#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct VFSFileHandle {
    pub fd: u32,
    pub inode: *mut VFSInode,
    pub offset: size_t,
    pub flags: u32,
    pub is_open: bool,
}

#[repr(C)]
pub struct VFSState {
    pub runtime: *mut GPUHotRuntime,
    pub inodes: [VFSInode; 1024],
    pub num_inodes: u32,
    pub root: *mut VFSInode,
    pub open_files: [VFSFileHandle; 256],
    pub num_open_files: u32,
    pub next_fd: u32,
    pub reads: u64,
    pub writes: u64,
    pub opens: u64,
    pub closes: u64,
}

#[repr(C)]
#[derive(Debug)]
pub struct PTXSystemState {
    pub auth_token: u32,
    pub active_processes: c_int,
    pub active_tasks: c_int,
    pub max_priority_active: c_int,
    pub total_vram_used: size_t,
    pub watchdog_alert: bool,
    pub kernel_running: bool,
    pub shutdown_requested: bool,
    pub active_priority_level: c_int,
    pub signal_mask: u64,
    pub interrupt_cnt: u32,
    pub queue: PTXTaskQueue,
    pub total_ops: u64,
    pub fs_node_count: u32,
    pub vmm: *mut VMMState,
    pub vfs: *mut VFSState,
}

#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct GPUHotStats {
    pub vram_allocated: size_t,
    pub vram_used: size_t,
    pub vram_free: size_t,
    pub gpu_utilization: f32,
    pub mem_utilization: f32,
    pub sm_clock_mhz: u32,
    pub mem_clock_mhz: u32,
    pub power_w: f32,
    pub temperature_c: i32,
    pub nvml_valid: bool,
    pub hw_ops_per_sec: f32,
    pub gflops_total: f32,
    pub cupti_valid: bool,
    pub active_streams: c_int,
    pub stream_poll_count: c_int,
    pub stream_busy: [u8; 128],
    pub registered_kernels: c_int,
    pub shm_count: c_int,
    pub total_ops: u64,
    pub avg_latency_us: f32,
    pub watchdog_tripped: bool,
}

impl Default for GPUHotStats {
    fn default() -> Self {
        // SAFETY: all-zeros is valid for this C struct (matches memset behavior)
        unsafe { std::mem::zeroed() }
    }
}

#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct TLSFPoolStats {
    pub total_pool_size: size_t,
    pub allocated_bytes: size_t,
    pub free_bytes: size_t,
    pub peak_allocated: size_t,
    pub largest_free_block: size_t,
    pub smallest_free_block: size_t,
    pub total_blocks: u32,
    pub free_blocks: u32,
    pub allocated_blocks: u32,
    pub fallback_count: u32,
    pub utilization_percent: f32,
    pub fragmentation_ratio: f32,
    pub external_fragmentation: f32,
    pub free_list_counts: [u32; 34],  // Must match TLSF_FL_INDEX_MAX=34
    pub hash_collisions: u32,
    pub max_chain_length: u32,
    pub avg_chain_length: f32,
    pub total_allocations: u64,
    pub total_frees: u64,
    pub total_splits: u32,
    pub total_merges: u32,
    pub is_healthy: bool,
    pub needs_defrag: bool,
}

impl Default for TLSFPoolStats {
    fn default() -> Self {
        Self {
            total_pool_size: 0,
            allocated_bytes: 0,
            free_bytes: 0,
            peak_allocated: 0,
            largest_free_block: 0,
            smallest_free_block: 0,
            total_blocks: 0,
            free_blocks: 0,
            allocated_blocks: 0,
            fallback_count: 0,
            utilization_percent: 0.0,
            fragmentation_ratio: 0.0,
            external_fragmentation: 0.0,
            free_list_counts: [0; 34],
            hash_collisions: 0,
            max_chain_length: 0,
            avg_chain_length: 0.0,
            total_allocations: 0,
            total_frees: 0,
            total_splits: 0,
            total_merges: 0,
            is_healthy: false,
            needs_defrag: false,
        }
    }
}

pub const TLSF_MAX_OWNERS: usize = 64;
pub const TLSF_EVENT_RING_SIZE: usize = 256;

#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct TLSFOwnerUsage {
    pub owner_id: u32,
    pub allocated_bytes: size_t,
    pub block_count: u32,
}

#[repr(C)]
#[derive(Clone)]
pub struct TLSFOwnerStats {
    pub owners: [TLSFOwnerUsage; TLSF_MAX_OWNERS],
    pub num_owners: u32,
}

impl Default for TLSFOwnerStats {
    fn default() -> Self {
        unsafe { std::mem::zeroed() }
    }
}

#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct TLSFAllocEvent {
    pub timestamp: u64,
    pub size: size_t,
    pub owner_id: u32,
    pub alloc_id: u32,
    pub event_type: u8,
    pub _pad: [u8; 3],
}

#[repr(C)]
#[derive(Clone)]
pub struct TLSFEventRing {
    pub events: [TLSFAllocEvent; TLSF_EVENT_RING_SIZE],
    pub head: u32,
    pub count: u32,
}

impl Default for TLSFEventRing {
    fn default() -> Self {
        unsafe { std::mem::zeroed() }
    }
}

#[repr(C)]
#[derive(Debug, Clone)]
pub struct TLSFHealthReport {
    pub is_valid: bool,
    pub has_memory_leaks: bool,
    pub has_corrupted_blocks: bool,
    pub has_broken_chains: bool,
    pub has_hash_errors: bool,
    pub error_count: c_int,
    pub error_messages: [[c_char; 256]; 16],
}

impl Default for TLSFHealthReport {
    fn default() -> Self {
        Self {
            is_valid: true,
            has_memory_leaks: false,
            has_corrupted_blocks: false,
            has_broken_chains: false,
            has_hash_errors: false,
            error_count: 0,
            error_messages: [[0; 256]; 16],
        }
    }
}

#[repr(C)]
#[derive(Debug, Copy, Clone, Default)]
pub struct GPUHotSystemSnapshot {
    pub total_ops: u64,
    pub active_processes: c_int,
    pub active_tasks: c_int,
    pub max_priority_active: c_int,
    pub total_vram_used: size_t,
    pub watchdog_alert: bool,
    pub kernel_running: bool,
    pub shutdown_requested: bool,
    pub active_priority_level: c_int,
    pub signal_mask: u64,
    pub interrupt_cnt: u32,
    pub queue_head: u32,
    pub queue_tail: u32,
    pub queue_lock: u32,
}

/// Context hook statistics - tracks blocked creates, prevented switches, etc.
#[repr(C)]
#[derive(Debug, Copy, Clone, Default)]
pub struct PTXContextStats {
    pub ctx_create_blocked: u64,
    pub ctx_create_passthrough: u64,
    pub ctx_destroy_blocked: u64,
    pub ctx_switch_prevented: u64,
    pub ctx_switch_substituted: u64,
    pub primary_retain_intercepted: u64,
    pub primary_release_suppressed: u64,
    pub primary_reset_blocked: u64,
    pub primary_setflags_blocked: u64,
    pub push_substituted: u64,
    pub pop_corrected: u64,
}

#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct GPUHotConfig {
    pub pool_fraction: f32,
    pub fixed_pool_size: size_t,
    pub min_pool_size: size_t,
    pub max_pool_size: size_t,
    pub reserve_vram: size_t,
    pub enable_leak_detection: bool,
    pub enable_pool_health: bool,
    pub warning_threshold: f32,
    pub force_daemon_mode: bool,
    pub quiet_init: bool,
    pub max_streams: u32,
    pub single_pool_strict: bool,
    pub prefer_orin_unified_memory: bool,
    pub use_managed_pool: bool,
}

impl Default for GPUHotConfig {
    fn default() -> Self {
        Self {
            pool_fraction: 1.0, // Must match C gpu_hot_default_config()
            fixed_pool_size: 0,
            min_pool_size: 256 * 1024 * 1024,
            max_pool_size: 0,
            reserve_vram: 0,
            enable_leak_detection: true,
            enable_pool_health: true,
            warning_threshold: 0.9,
            force_daemon_mode: false,
            quiet_init: false,
            max_streams: 16, // Must match C gpu_hot_default_config(); GPU_HOT_MAX_STREAMS is the cap, not the default
            single_pool_strict: false,
            prefer_orin_unified_memory: false,
            use_managed_pool: false,
        }
    }
}

#[repr(C)]
#[derive(Debug, Copy, Clone, Default)]
pub struct PTXTensorDesc {
    pub data: *mut c_void,
    pub elem_count: size_t,
    pub dtype: PTXDType,
    pub ndim: u32,
    pub shape: [u32; 8],
    pub strides: [u32; 8],
    pub is_contiguous: bool,
}

#[repr(C)]
#[derive(Debug, Copy, Clone, Default)]
pub struct PTXTensorOp {
    pub opcode: PTXTensorOpcode,
    pub dtype: PTXDType,
    pub input_a: *mut c_void,
    pub input_b: *mut c_void,
    pub output: *mut c_void,
    pub elem_count: size_t,
    pub scalar_a: f32,
    pub scalar_b: f32,
    pub reduce_dim: u32,
    pub reduce_size: u32,
    pub outer_size: u32,
    pub inner_size: u32,
    pub stream: cudaStream_t,
}

// ============================================================================
// External Functions
// ============================================================================

extern "C" {
    // Stable Runtime ABI
    pub fn ptx_stable_runtime_version() -> *const c_char;
    pub fn ptx_stable_runtime_abi_version() -> u32;
    pub fn ptx_stable_strerror(status: PTXStableStatus) -> *const c_char;
    pub fn ptx_stable_init(
        config: *const PTXStableConfig,
        out_runtime: *mut *mut PTXStableRuntime,
    ) -> PTXStableStatus;
    pub fn ptx_stable_retain(out_runtime: *mut *mut PTXStableRuntime) -> PTXStableStatus;
    pub fn ptx_stable_release(runtime: *mut PTXStableRuntime) -> PTXStableStatus;
    pub fn ptx_stable_get(out_runtime: *mut *mut PTXStableRuntime) -> PTXStableStatus;
    pub fn ptx_stable_alloc(
        runtime: *mut PTXStableRuntime,
        size: size_t,
        out_ptr: *mut *mut c_void,
    ) -> PTXStableStatus;
    pub fn ptx_stable_free(runtime: *mut PTXStableRuntime, ptr: *mut c_void) -> PTXStableStatus;
    pub fn ptx_stable_owns_ptr(
        runtime: *mut PTXStableRuntime,
        ptr: *const c_void,
        out_owned: *mut bool,
    ) -> PTXStableStatus;
    pub fn ptx_stable_get_context(
        runtime: *mut PTXStableRuntime,
        out_cu_context: *mut *mut c_void,
    ) -> PTXStableStatus;
    pub fn ptx_stable_get_stats(
        runtime: *mut PTXStableRuntime,
        out_stats: *mut PTXStableStats,
    ) -> PTXStableStatus;
    pub fn ptx_stable_get_hot_runtime(
        runtime: *mut PTXStableRuntime,
        out_gpu_hot_runtime: *mut *mut c_void,
    ) -> PTXStableStatus;

    // Core Runtime API
    pub fn gpu_hot_init(device_id: c_int, token: *const c_char) -> *mut GPUHotRuntime;
    pub fn gpu_hot_init_with_config(
        device_id: c_int,
        token: *const c_char,
        config: *const GPUHotConfig,
    ) -> *mut GPUHotRuntime;
    pub fn gpu_hot_shutdown(runtime: *mut GPUHotRuntime);
    pub fn gpu_hot_keepalive(runtime: *mut GPUHotRuntime);
    pub fn gpu_hot_default_config() -> GPUHotConfig;

    // Memory Allocation API
    pub fn gpu_hot_alloc(runtime: *mut GPUHotRuntime, size: size_t) -> *mut c_void;
    pub fn gpu_hot_free(runtime: *mut GPUHotRuntime, ptr: *mut c_void);
    pub fn gpu_hot_alloc_async(
        runtime: *mut GPUHotRuntime,
        size: size_t,
        stream: cudaStream_t,
    ) -> *mut c_void;
    pub fn gpu_hot_free_async(runtime: *mut GPUHotRuntime, ptr: *mut c_void, stream: cudaStream_t);
    pub fn gpu_hot_poll_deferred(runtime: *mut GPUHotRuntime, max_drain: c_int);
    pub fn gpu_hot_can_allocate(runtime: *mut GPUHotRuntime, size: size_t) -> bool;
    pub fn gpu_hot_get_max_allocatable(runtime: *mut GPUHotRuntime) -> size_t;
    pub fn gpu_hot_owns_ptr(runtime: *mut GPUHotRuntime, ptr: *mut c_void) -> bool;

    // Per-owner allocation API
    pub fn gpu_hot_alloc_owned(
        runtime: *mut GPUHotRuntime,
        size: size_t,
        owner_id: u32,
    ) -> *mut c_void;
    pub fn gpu_hot_free_owner(runtime: *mut GPUHotRuntime, owner_id: u32);
    pub fn gpu_hot_get_owner_stats(runtime: *mut GPUHotRuntime, stats: *mut TLSFOwnerStats);

    // Allocation event log
    pub fn gpu_hot_get_alloc_events(runtime: *mut GPUHotRuntime, ring_out: *mut TLSFEventRing);

    // CUDA Allocation Hook API
    pub fn ptx_hook_init(runtime: *mut GPUHotRuntime, verbose: bool);
    pub fn ptx_hook_disable();
    pub fn ptx_hook_owns_ptr(ptr: *mut c_void) -> bool;

    // Kernel Registration & Launch API
    pub fn gpu_hot_register_kernel(
        runtime: *mut GPUHotRuntime,
        kernel_func: *mut c_void,
        grid: dim3,
        block: dim3,
        shared_mem: size_t,
    ) -> c_int;
    pub fn gpu_hot_launch_kernel(
        runtime: *mut GPUHotRuntime,
        kernel_id: c_int,
        args: *mut *mut c_void,
    );

    // CUDA Graph API
    pub fn gpu_hot_begin_capture(
        runtime: *mut GPUHotRuntime,
        stream_id: c_int,
        graph_name: *const c_char,
    ) -> c_int;
    pub fn gpu_hot_end_capture(runtime: *mut GPUHotRuntime, stream_id: c_int) -> c_int;
    pub fn gpu_hot_launch_graph(
        runtime: *mut GPUHotRuntime,
        graph_id: c_int,
        stream: cudaStream_t,
    );
    pub fn gpu_hot_destroy_graph(runtime: *mut GPUHotRuntime, graph_id: c_int);

    // Stream API
    pub fn gpu_hot_get_stream(runtime: *mut GPUHotRuntime, stream_id: c_int) -> cudaStream_t;
    pub fn gpu_hot_get_priority_stream(
        runtime: *mut GPUHotRuntime,
        priority: c_int,
    ) -> cudaStream_t;
    pub fn gpu_hot_sync_all(runtime: *mut GPUHotRuntime);

    // Statistics API
    pub fn gpu_hot_get_stats(runtime: *mut GPUHotRuntime, stats: *mut GPUHotStats);
    pub fn gpu_hot_get_tlsf_stats(runtime: *mut GPUHotRuntime, stats: *mut TLSFPoolStats);
    pub fn gpu_hot_validate_tlsf_pool(runtime: *mut GPUHotRuntime, report: *mut TLSFHealthReport);
    pub fn gpu_hot_print_pool_map(runtime: *mut GPUHotRuntime);

    // TLSF Pool Management
    pub fn gpu_hot_defragment_pool(runtime: *mut GPUHotRuntime);
    pub fn gpu_hot_set_warning_threshold(runtime: *mut GPUHotRuntime, threshold_percent: f32);
    pub fn gpu_hot_set_auto_defrag(runtime: *mut GPUHotRuntime, enable: bool);

    // Shared Memory / IPC API
    pub fn gpu_hot_shm_alloc(
        runtime: *mut GPUHotRuntime,
        name: *const c_char,
        size: size_t,
    ) -> *mut c_void;
    pub fn gpu_hot_shm_open(runtime: *mut GPUHotRuntime, name: *const c_char) -> *mut c_void;
    pub fn gpu_hot_shm_close(runtime: *mut GPUHotRuntime, ptr: *mut c_void);
    pub fn gpu_hot_shm_unlink(runtime: *mut GPUHotRuntime, name: *const c_char);
    pub fn gpu_hot_get_registry_entry(
        runtime: *mut GPUHotRuntime,
        index: c_int,
        name_out: *mut c_char,
        size_out: *mut size_t,
        active_out: *mut bool,
        created_out: *mut u64,
    ) -> bool;

    // Watchdog API
    pub fn gpu_hot_set_watchdog(runtime: *mut GPUHotRuntime, timeout_ms: c_int);
    pub fn gpu_hot_check_watchdog(runtime: *mut GPUHotRuntime) -> bool;
    pub fn gpu_hot_reset_watchdog(runtime: *mut GPUHotRuntime);

    // System State API
    pub fn gpu_hot_get_system_state(runtime: *mut GPUHotRuntime) -> *mut PTXSystemState;
    pub fn gpu_hot_get_host_system_state(runtime: *mut GPUHotRuntime) -> *mut PTXSystemState;
    pub fn gpu_hot_reset_system_state(runtime: *mut GPUHotRuntime);
    pub fn gpu_hot_flush_task_queue(runtime: *mut GPUHotRuntime);
    pub fn gpu_hot_clear_signal_mask(runtime: *mut GPUHotRuntime);
    pub fn gpu_hot_get_system_snapshot(
        runtime: *mut GPUHotRuntime,
        snapshot: *mut GPUHotSystemSnapshot,
    );

    // PTX-OS Kernel Boot
    pub fn ptx_os_boot_persistent_kernel(runtime: *mut GPUHotRuntime);
    pub fn ptx_os_submit_task(
        runtime: *mut GPUHotRuntime,
        opcode: u32,
        priority: u32,
        args: *mut *mut c_void,
    ) -> c_int;

    // CUDA Dynamic Parallelism — Device-Side Self-Scheduling
    pub fn ptx_cdp_test_recursive(
        runtime: *mut GPUHotRuntime,
        iterations: c_int,
    ) -> c_int;

    // Context Export API
    pub fn gpu_hot_get_context(runtime: *mut GPUHotRuntime) -> *mut c_void;
    pub fn gpu_hot_export_context(runtime: *mut GPUHotRuntime);

    // Context Hook API (weak - only available when libptx_hook.so is loaded)
    // These are called via the runtime wrapper, not directly.
    pub fn ptx_context_hook_get_stats(stats: *mut PTXContextStats);
    pub fn ptx_context_hook_reset_stats();

    // VMM API
    pub fn vmm_init(runtime: *mut GPUHotRuntime, swap_size: size_t) -> *mut VMMState;
    pub fn vmm_shutdown(vmm: *mut VMMState);
    pub fn vmm_alloc_page(vmm: *mut VMMState, flags: u32) -> *mut c_void;
    pub fn vmm_free_page(vmm: *mut VMMState, addr: *mut c_void);
    pub fn vmm_swap_out(vmm: *mut VMMState, addr: *mut c_void) -> c_int;
    pub fn vmm_swap_in(vmm: *mut VMMState, addr: *mut c_void) -> c_int;
    pub fn vmm_pin_page(vmm: *mut VMMState, addr: *mut c_void);
    pub fn vmm_unpin_page(vmm: *mut VMMState, addr: *mut c_void);
    pub fn vmm_get_stats(
        vmm: *mut VMMState,
        resident: *mut u64,
        swapped: *mut u64,
        faults: *mut u64,
        evictions: *mut u64,
    );
    pub fn gpu_hot_set_vmm(runtime: *mut GPUHotRuntime, vmm: *mut VMMState);
    pub fn vmm_evict_for_alloc(vmm: *mut VMMState, needed_size: size_t) -> c_int;

    // VFS API
    pub fn vfs_init(runtime: *mut GPUHotRuntime) -> *mut VFSState;
    pub fn vfs_shutdown(vfs: *mut VFSState);
    pub fn vfs_lookup(vfs: *mut VFSState, path: *const c_char) -> *mut VFSInode;
    pub fn vfs_mkdir(vfs: *mut VFSState, path: *const c_char, mode: u32) -> c_int;
    pub fn vfs_rmdir(vfs: *mut VFSState, path: *const c_char) -> c_int;
    pub fn vfs_unlink(vfs: *mut VFSState, path: *const c_char) -> c_int;
    pub fn vfs_open(vfs: *mut VFSState, path: *const c_char, flags: u32) -> c_int;
    pub fn vfs_close(vfs: *mut VFSState, fd: c_int) -> c_int;
    pub fn vfs_read(vfs: *mut VFSState, fd: c_int, buf: *mut c_void, count: size_t) -> ssize_t;
    pub fn vfs_write(vfs: *mut VFSState, fd: c_int, buf: *const c_void, count: size_t) -> ssize_t;
    pub fn vfs_seek(vfs: *mut VFSState, fd: c_int, offset: size_t, whence: c_int) -> c_int;
    pub fn vfs_create_tensor(
        vfs: *mut VFSState,
        path: *const c_char,
        shape: *mut c_int,
        dims: c_int,
        dtype: c_int,
    ) -> c_int;
    pub fn vfs_mmap_tensor(vfs: *mut VFSState, path: *const c_char) -> *mut c_void;
    pub fn vfs_sync_tensor(vfs: *mut VFSState, path: *const c_char) -> c_int;
    pub fn vfs_readdir(
        vfs: *mut VFSState,
        path: *const c_char,
        names: *mut *mut c_char,
        max_entries: c_int,
    ) -> c_int;
    pub fn vfs_stat(vfs: *mut VFSState, path: *const c_char, stat_out: *mut VFSInode) -> c_int;

    // Tensor Operations - Binary F32
    pub fn ptx_tensor_add_f32(
        a: *mut f32,
        b: *mut f32,
        out: *mut f32,
        n: size_t,
        stream: cudaStream_t,
    );
    pub fn ptx_tensor_sub_f32(
        a: *mut f32,
        b: *mut f32,
        out: *mut f32,
        n: size_t,
        stream: cudaStream_t,
    );
    pub fn ptx_tensor_mul_f32(
        a: *mut f32,
        b: *mut f32,
        out: *mut f32,
        n: size_t,
        stream: cudaStream_t,
    );
    pub fn ptx_tensor_div_f32(
        a: *mut f32,
        b: *mut f32,
        out: *mut f32,
        n: size_t,
        stream: cudaStream_t,
    );
    pub fn ptx_tensor_max_f32(
        a: *mut f32,
        b: *mut f32,
        out: *mut f32,
        n: size_t,
        stream: cudaStream_t,
    );
    pub fn ptx_tensor_min_f32(
        a: *mut f32,
        b: *mut f32,
        out: *mut f32,
        n: size_t,
        stream: cudaStream_t,
    );
    pub fn ptx_tensor_mod_f32(
        a: *mut f32,
        b: *mut f32,
        out: *mut f32,
        n: size_t,
        stream: cudaStream_t,
    );

    // Tensor Operations - Unary F32
    pub fn ptx_tensor_neg_f32(input: *mut f32, out: *mut f32, n: size_t, stream: cudaStream_t);
    pub fn ptx_tensor_abs_f32(input: *mut f32, out: *mut f32, n: size_t, stream: cudaStream_t);
    pub fn ptx_tensor_exp_f32(input: *mut f32, out: *mut f32, n: size_t, stream: cudaStream_t);
    pub fn ptx_tensor_log_f32(input: *mut f32, out: *mut f32, n: size_t, stream: cudaStream_t);
    pub fn ptx_tensor_sqrt_f32(input: *mut f32, out: *mut f32, n: size_t, stream: cudaStream_t);
    pub fn ptx_tensor_rsqrt_f32(input: *mut f32, out: *mut f32, n: size_t, stream: cudaStream_t);
    pub fn ptx_tensor_sin_f32(input: *mut f32, out: *mut f32, n: size_t, stream: cudaStream_t);
    pub fn ptx_tensor_cos_f32(input: *mut f32, out: *mut f32, n: size_t, stream: cudaStream_t);
    pub fn ptx_tensor_tanh_f32(input: *mut f32, out: *mut f32, n: size_t, stream: cudaStream_t);
    pub fn ptx_tensor_ceil_f32(input: *mut f32, out: *mut f32, n: size_t, stream: cudaStream_t);
    pub fn ptx_tensor_floor_f32(input: *mut f32, out: *mut f32, n: size_t, stream: cudaStream_t);
    pub fn ptx_tensor_round_f32(input: *mut f32, out: *mut f32, n: size_t, stream: cudaStream_t);
    pub fn ptx_tensor_sqr_f32(input: *mut f32, out: *mut f32, n: size_t, stream: cudaStream_t);
    pub fn ptx_tensor_recip_f32(input: *mut f32, out: *mut f32, n: size_t, stream: cudaStream_t);
    pub fn ptx_tensor_log2_f32(input: *mut f32, out: *mut f32, n: size_t, stream: cudaStream_t);
    pub fn ptx_tensor_log10_f32(input: *mut f32, out: *mut f32, n: size_t, stream: cudaStream_t);
    pub fn ptx_tensor_tan_f32(input: *mut f32, out: *mut f32, n: size_t, stream: cudaStream_t);
    pub fn ptx_tensor_sinh_f32(input: *mut f32, out: *mut f32, n: size_t, stream: cudaStream_t);
    pub fn ptx_tensor_cosh_f32(input: *mut f32, out: *mut f32, n: size_t, stream: cudaStream_t);
    pub fn ptx_tensor_sign_f32(input: *mut f32, out: *mut f32, n: size_t, stream: cudaStream_t);
    pub fn ptx_tensor_erf_f32(input: *mut f32, out: *mut f32, n: size_t, stream: cudaStream_t);

    // Tensor Operations - Activations F32
    pub fn ptx_tensor_relu_f32(input: *mut f32, out: *mut f32, n: size_t, stream: cudaStream_t);
    pub fn ptx_tensor_relu6_f32(input: *mut f32, out: *mut f32, n: size_t, stream: cudaStream_t);
    pub fn ptx_tensor_leaky_relu_f32(
        input: *mut f32,
        out: *mut f32,
        n: size_t,
        alpha: f32,
        stream: cudaStream_t,
    );
    pub fn ptx_tensor_elu_f32(
        input: *mut f32,
        out: *mut f32,
        n: size_t,
        alpha: f32,
        stream: cudaStream_t,
    );
    pub fn ptx_tensor_selu_f32(input: *mut f32, out: *mut f32, n: size_t, stream: cudaStream_t);
    pub fn ptx_tensor_gelu_f32(input: *mut f32, out: *mut f32, n: size_t, stream: cudaStream_t);
    pub fn ptx_tensor_sigmoid_f32(input: *mut f32, out: *mut f32, n: size_t, stream: cudaStream_t);
    pub fn ptx_tensor_silu_f32(input: *mut f32, out: *mut f32, n: size_t, stream: cudaStream_t);
    pub fn ptx_tensor_softplus_f32(input: *mut f32, out: *mut f32, n: size_t, stream: cudaStream_t);
    pub fn ptx_tensor_mish_f32(input: *mut f32, out: *mut f32, n: size_t, stream: cudaStream_t);
    pub fn ptx_tensor_gelu_tanh_f32(input: *mut f32, out: *mut f32, n: size_t, stream: cudaStream_t);
    pub fn ptx_tensor_hardswish_f32(input: *mut f32, out: *mut f32, n: size_t, stream: cudaStream_t);
    pub fn ptx_tensor_hardsigmoid_f32(input: *mut f32, out: *mut f32, n: size_t, stream: cudaStream_t);

    // Tensor Operations - Reductions F32
    pub fn ptx_tensor_reduce_sum_f32(
        input: *mut f32,
        out: *mut f32,
        outer: size_t,
        reduce: size_t,
        inner: size_t,
        stream: cudaStream_t,
    );
    pub fn ptx_tensor_reduce_mean_f32(
        input: *mut f32,
        out: *mut f32,
        outer: size_t,
        reduce: size_t,
        inner: size_t,
        stream: cudaStream_t,
    );
    pub fn ptx_tensor_reduce_max_f32(
        input: *mut f32,
        out: *mut f32,
        outer: size_t,
        reduce: size_t,
        inner: size_t,
        stream: cudaStream_t,
    );
    pub fn ptx_tensor_reduce_min_f32(
        input: *mut f32,
        out: *mut f32,
        outer: size_t,
        reduce: size_t,
        inner: size_t,
        stream: cudaStream_t,
    );
    pub fn ptx_tensor_reduce_prod_f32(
        input: *mut f32,
        out: *mut f32,
        outer: size_t,
        reduce: size_t,
        inner: size_t,
        stream: cudaStream_t,
    );
    pub fn ptx_tensor_reduce_argmax_f32(
        input: *mut f32,
        out: *mut i32,
        outer: size_t,
        reduce: size_t,
        inner: size_t,
        stream: cudaStream_t,
    );
    pub fn ptx_tensor_reduce_argmin_f32(
        input: *mut f32,
        out: *mut i32,
        outer: size_t,
        reduce: size_t,
        inner: size_t,
        stream: cudaStream_t,
    );

    // Tensor Operations - Gather/Scatter F32
    pub fn ptx_tensor_gather_f32(
        input: *mut f32,
        indices: *mut i32,
        out: *mut f32,
        outer: size_t,
        input_dim_size: size_t,
        idx_dim_size: size_t,
        inner: size_t,
        stream: cudaStream_t,
    );

    // Tensor Operations - Scan/Prefix F32
    pub fn ptx_tensor_cumsum_f32(
        input: *mut f32,
        out: *mut f32,
        outer: size_t,
        dim_size: size_t,
        inner: size_t,
        stream: cudaStream_t,
    );

    // Tensor Operations - IndexSelect/ScatterAdd/IndexAdd F32
    pub fn ptx_tensor_index_select_f32(
        input: *mut f32,
        ids: *mut i32,
        output: *mut f32,
        left_size: size_t,
        src_dim_size: size_t,
        ids_dim_size: size_t,
        right_size: size_t,
        stream: cudaStream_t,
    );
    pub fn ptx_tensor_scatter_add_f32(
        ids: *mut i32,
        src: *mut f32,
        output: *mut f32,
        left_size: size_t,
        src_dim_size: size_t,
        dst_dim_size: size_t,
        right_size: size_t,
        stream: cudaStream_t,
    );

    // Tensor Operations - Argsort F32
    pub fn ptx_tensor_argsort_f32(
        input: *mut f32,
        output: *mut u32,
        nrows: size_t,
        ncols: size_t,
        ascending: libc::c_int,
        stream: cudaStream_t,
    );

    // Tensor Operations - TopK/Selection F32
    pub fn ptx_tensor_topk_f32(
        input: *mut f32,
        values_out: *mut f32,
        indices_out: *mut i32,
        outer: size_t,
        dim_size: size_t,
        inner: size_t,
        k: size_t,
        largest: libc::c_int,
        stream: cudaStream_t,
    );

    // Tensor Operations - Softmax F32
    pub fn ptx_tensor_softmax_f32(
        input: *mut f32,
        out: *mut f32,
        batch: size_t,
        dim: size_t,
        stream: cudaStream_t,
    );
    pub fn ptx_tensor_log_softmax_f32(
        input: *mut f32,
        out: *mut f32,
        batch: size_t,
        dim: size_t,
        stream: cudaStream_t,
    );

    // Tensor Operations - Transform F32
    pub fn ptx_tensor_affine_f32(
        input: *mut f32,
        out: *mut f32,
        n: size_t,
        mul: f32,
        add: f32,
        stream: cudaStream_t,
    );
    pub fn ptx_tensor_clamp_f32(
        input: *mut f32,
        out: *mut f32,
        n: size_t,
        min_val: f32,
        max_val: f32,
        stream: cudaStream_t,
    );
    pub fn ptx_tensor_powf_f32(
        input: *mut f32,
        out: *mut f32,
        n: size_t,
        exp: f32,
        stream: cudaStream_t,
    );

    // Tensor Operations - Comparison F32
    pub fn ptx_tensor_cmp_eq_f32(
        a: *mut f32,
        b: *mut f32,
        out: *mut u8,
        n: size_t,
        stream: cudaStream_t,
    );
    pub fn ptx_tensor_cmp_lt_f32(
        a: *mut f32,
        b: *mut f32,
        out: *mut u8,
        n: size_t,
        stream: cudaStream_t,
    );
    pub fn ptx_tensor_cmp_le_f32(
        a: *mut f32,
        b: *mut f32,
        out: *mut u8,
        n: size_t,
        stream: cudaStream_t,
    );
    pub fn ptx_tensor_cmp_gt_f32(
        a: *mut f32,
        b: *mut f32,
        out: *mut u8,
        n: size_t,
        stream: cudaStream_t,
    );
    pub fn ptx_tensor_cmp_ge_f32(
        a: *mut f32,
        b: *mut f32,
        out: *mut u8,
        n: size_t,
        stream: cudaStream_t,
    );
    pub fn ptx_tensor_cmp_ne_f32(
        a: *mut f32,
        b: *mut f32,
        out: *mut u8,
        n: size_t,
        stream: cudaStream_t,
    );

    // Tensor Operations - Where/Select
    pub fn ptx_tensor_where_f32(
        cond: *mut u8,
        t: *mut f32,
        f: *mut f32,
        out: *mut f32,
        n: size_t,
        stream: cudaStream_t,
    );

    // Tensor Operations - Copy/Fill
    pub fn ptx_tensor_copy_f32(input: *mut f32, out: *mut f32, n: size_t, stream: cudaStream_t);
    pub fn ptx_tensor_fill_f32(out: *mut f32, n: size_t, value: f32, stream: cudaStream_t);

    // Tensor Operations - Strided Copy (for making non-contiguous tensors contiguous)
    pub fn ptx_tensor_strided_copy_f32(
        input: *const f32, out: *mut f32,
        shape: *const size_t, in_strides: *const size_t,
        ndim: i32, n: size_t, stream: cudaStream_t,
    );
    pub fn ptx_tensor_strided_copy_f64(
        input: *const f64, out: *mut f64,
        shape: *const size_t, in_strides: *const size_t,
        ndim: i32, n: size_t, stream: cudaStream_t,
    );
    pub fn ptx_tensor_strided_copy_u8(
        input: *const u8, out: *mut u8,
        shape: *const size_t, in_strides: *const size_t,
        ndim: i32, n: size_t, stream: cudaStream_t,
    );
    pub fn ptx_tensor_cast_f32_to_f16(
        input: *mut f32,
        out: *mut __half,
        n: size_t,
        stream: cudaStream_t,
    );
    pub fn ptx_tensor_cast_f16_to_f32(
        input: *mut __half,
        out: *mut f32,
        n: size_t,
        stream: cudaStream_t,
    );

    // Tensor Operations - Scan (cumprod, cummax, cummin)
    pub fn ptx_tensor_cumprod_f32(input: *mut f32, out: *mut f32, outer: size_t, dim_size: size_t, inner: size_t, stream: cudaStream_t);
    pub fn ptx_tensor_cummax_f32(input: *mut f32, out: *mut f32, outer: size_t, dim_size: size_t, inner: size_t, stream: cudaStream_t);
    pub fn ptx_tensor_cummin_f32(input: *mut f32, out: *mut f32, outer: size_t, dim_size: size_t, inner: size_t, stream: cudaStream_t);

    // Tensor Operations - Cast (additional)
    pub fn ptx_tensor_cast_f32_to_i32(input: *mut f32, out: *mut i32, n: size_t, stream: cudaStream_t);
    pub fn ptx_tensor_cast_i32_to_f32(input: *mut i32, out: *mut f32, n: size_t, stream: cudaStream_t);

    // Tensor Operations - Random
    pub fn ptx_tensor_rand_f32(out: *mut f32, n: size_t, seed: u64, stream: cudaStream_t);
    pub fn ptx_tensor_randn_f32(out: *mut f32, n: size_t, seed: u64, stream: cudaStream_t);

    // Tensor Operations - Arange
    pub fn ptx_tensor_arange_f32(out: *mut f32, n: size_t, start: f32, step: f32, stream: cudaStream_t);

    // Tensor Operations - Logical (U8 boolean tensors)
    pub fn ptx_tensor_logical_and_u8(a: *mut u8, b: *mut u8, out: *mut u8, n: size_t, stream: cudaStream_t);
    pub fn ptx_tensor_logical_or_u8(a: *mut u8, b: *mut u8, out: *mut u8, n: size_t, stream: cudaStream_t);
    pub fn ptx_tensor_logical_not_u8(input: *mut u8, out: *mut u8, n: size_t, stream: cudaStream_t);
    pub fn ptx_tensor_logical_xor_u8(a: *mut u8, b: *mut u8, out: *mut u8, n: size_t, stream: cudaStream_t);

    // Tensor Operations - Broadcast binary
    pub fn ptx_tensor_broadcast_binary_f32(
        a: *mut f32, b: *mut f32, out: *mut f32, n: size_t,
        out_shape: *mut size_t, a_strides: *mut size_t, b_strides: *mut size_t,
        ndim: i32, op: i32, stream: cudaStream_t,
    );

    // Tensor Operations - Pad
    pub fn ptx_tensor_pad2d_f32(
        input: *mut f32, out: *mut f32,
        n: i32, c: i32, h: i32, w: i32,
        pad_top: i32, pad_bottom: i32, pad_left: i32, pad_right: i32,
        pad_value: f32, stream: cudaStream_t,
    );

    // Tensor Operations - Repeat/Tile
    pub fn ptx_tensor_repeat_f32(
        input: *mut f32, out: *mut f32, out_n: size_t,
        in_shape: *mut size_t, out_shape: *mut size_t, ndim: i32, stream: cudaStream_t,
    );

    // Tensor Operations - Masked fill
    pub fn ptx_tensor_masked_fill_f32(data: *mut f32, mask: *mut u8, value: f32, n: size_t, stream: cudaStream_t);

    // Tensor Operations - Scalar Broadcast F32
    pub fn ptx_tensor_add_scalar_f32(
        a: *mut f32,
        scalar: f32,
        out: *mut f32,
        n: size_t,
        stream: cudaStream_t,
    );
    pub fn ptx_tensor_sub_scalar_f32(
        a: *mut f32,
        scalar: f32,
        out: *mut f32,
        n: size_t,
        stream: cudaStream_t,
    );
    pub fn ptx_tensor_mul_scalar_f32(
        a: *mut f32,
        scalar: f32,
        out: *mut f32,
        n: size_t,
        stream: cudaStream_t,
    );
    pub fn ptx_tensor_div_scalar_f32(
        a: *mut f32,
        scalar: f32,
        out: *mut f32,
        n: size_t,
        stream: cudaStream_t,
    );

    // Tensor Operations - F64 variants
    pub fn ptx_tensor_add_f64(
        a: *mut f64,
        b: *mut f64,
        out: *mut f64,
        n: size_t,
        stream: cudaStream_t,
    );
    pub fn ptx_tensor_sub_f64(
        a: *mut f64,
        b: *mut f64,
        out: *mut f64,
        n: size_t,
        stream: cudaStream_t,
    );
    pub fn ptx_tensor_mul_f64(
        a: *mut f64,
        b: *mut f64,
        out: *mut f64,
        n: size_t,
        stream: cudaStream_t,
    );
    pub fn ptx_tensor_div_f64(
        a: *mut f64,
        b: *mut f64,
        out: *mut f64,
        n: size_t,
        stream: cudaStream_t,
    );
    pub fn ptx_tensor_neg_f64(input: *mut f64, out: *mut f64, n: size_t, stream: cudaStream_t);
    pub fn ptx_tensor_exp_f64(input: *mut f64, out: *mut f64, n: size_t, stream: cudaStream_t);
    pub fn ptx_tensor_log_f64(input: *mut f64, out: *mut f64, n: size_t, stream: cudaStream_t);
    pub fn ptx_tensor_sqrt_f64(input: *mut f64, out: *mut f64, n: size_t, stream: cudaStream_t);
    pub fn ptx_tensor_tanh_f64(input: *mut f64, out: *mut f64, n: size_t, stream: cudaStream_t);
    pub fn ptx_tensor_relu_f64(input: *mut f64, out: *mut f64, n: size_t, stream: cudaStream_t);
    pub fn ptx_tensor_gelu_f64(input: *mut f64, out: *mut f64, n: size_t, stream: cudaStream_t);
    pub fn ptx_tensor_sigmoid_f64(input: *mut f64, out: *mut f64, n: size_t, stream: cudaStream_t);
    pub fn ptx_tensor_reduce_sum_f64(
        input: *mut f64,
        out: *mut f64,
        outer: size_t,
        reduce: size_t,
        inner: size_t,
        stream: cudaStream_t,
    );
    pub fn ptx_tensor_reduce_max_f64(
        input: *mut f64,
        out: *mut f64,
        outer: size_t,
        reduce: size_t,
        inner: size_t,
        stream: cudaStream_t,
    );
    pub fn ptx_tensor_reduce_min_f64(
        input: *mut f64,
        out: *mut f64,
        outer: size_t,
        reduce: size_t,
        inner: size_t,
        stream: cudaStream_t,
    );
    pub fn ptx_tensor_softmax_f64(
        input: *mut f64,
        out: *mut f64,
        batch: size_t,
        dim: size_t,
        stream: cudaStream_t,
    );
    pub fn ptx_tensor_affine_f64(
        input: *mut f64,
        out: *mut f64,
        n: size_t,
        mul: f64,
        add: f64,
        stream: cudaStream_t,
    );

    // Tensor Operations - F16 variants
    pub fn ptx_tensor_add_f16(
        a: *mut __half,
        b: *mut __half,
        out: *mut __half,
        n: size_t,
        stream: cudaStream_t,
    );
    pub fn ptx_tensor_sub_f16(
        a: *mut __half,
        b: *mut __half,
        out: *mut __half,
        n: size_t,
        stream: cudaStream_t,
    );
    pub fn ptx_tensor_mul_f16(
        a: *mut __half,
        b: *mut __half,
        out: *mut __half,
        n: size_t,
        stream: cudaStream_t,
    );
    pub fn ptx_tensor_div_f16(
        a: *mut __half,
        b: *mut __half,
        out: *mut __half,
        n: size_t,
        stream: cudaStream_t,
    );
    pub fn ptx_tensor_relu_f16(
        input: *mut __half,
        out: *mut __half,
        n: size_t,
        stream: cudaStream_t,
    );
    pub fn ptx_tensor_gelu_f16(
        input: *mut __half,
        out: *mut __half,
        n: size_t,
        stream: cudaStream_t,
    );
    pub fn ptx_tensor_sigmoid_f16(
        input: *mut __half,
        out: *mut __half,
        n: size_t,
        stream: cudaStream_t,
    );
    pub fn ptx_tensor_softmax_f16(
        input: *mut __half,
        out: *mut __half,
        batch: size_t,
        dim: size_t,
        stream: cudaStream_t,
    );

    // Tensor Operations - Im2col / Col2im (Conv2d)
    pub fn ptx_tensor_im2col_f32(
        data_im: *const f32, data_col: *mut f32,
        n: i32, c: i32, h: i32, w: i32,
        kh: i32, kw: i32,
        pad_h: i32, pad_w: i32,
        stride_h: i32, stride_w: i32,
        dilation_h: i32, dilation_w: i32,
        h_out: i32, w_out: i32,
        stream: cudaStream_t,
    );
    pub fn ptx_tensor_col2im_f32(
        data_col: *const f32, data_im: *mut f32,
        n: i32, c: i32, h: i32, w: i32,
        kh: i32, kw: i32,
        pad_h: i32, pad_w: i32,
        stride_h: i32, stride_w: i32,
        dilation_h: i32, dilation_w: i32,
        h_out: i32, w_out: i32,
        stream: cudaStream_t,
    );

    // Tensor Operations - Pooling
    pub fn ptx_tensor_max_pool2d_f32(
        input: *const f32, output: *mut f32,
        n: i32, c: i32, h: i32, w: i32,
        kh: i32, kw: i32,
        stride_h: i32, stride_w: i32,
        pad_h: i32, pad_w: i32,
        h_out: i32, w_out: i32,
        stream: cudaStream_t,
    );
    pub fn ptx_tensor_avg_pool2d_f32(
        input: *const f32, output: *mut f32,
        n: i32, c: i32, h: i32, w: i32,
        kh: i32, kw: i32,
        stride_h: i32, stride_w: i32,
        pad_h: i32, pad_w: i32,
        h_out: i32, w_out: i32,
        stream: cudaStream_t,
    );

    // Tensor Operations - Optimizers
    pub fn ptx_tensor_sgd_step_f32(
        params: *mut f32, grads: *const f32, velocity: *mut f32,
        n: size_t, lr: f32, momentum: f32, weight_decay: f32,
        stream: cudaStream_t,
    );
    pub fn ptx_tensor_adam_step_f32(
        params: *mut f32, grads: *const f32, m: *mut f32, v: *mut f32,
        n: size_t, lr: f32, beta1: f32, beta2: f32, eps: f32, weight_decay: f32,
        bc1: f32, bc2: f32,
        stream: cudaStream_t,
    );

    // Generic Dispatch API
    pub fn ptx_tensor_dispatch(op: *const PTXTensorOp) -> cudaError_t;
    pub fn ptx_tensor_dispatch_sync(op: *const PTXTensorOp) -> cudaError_t;

    // CUDA Graph Integration
    pub fn ptx_tensor_graph_begin_capture(stream: cudaStream_t) -> cudaError_t;
    pub fn ptx_tensor_graph_end_capture(stream: cudaStream_t, graph_out: *mut cudaGraph_t)
        -> cudaError_t;
    pub fn ptx_tensor_graph_instantiate(
        graph: cudaGraph_t,
        exec_out: *mut cudaGraphExec_t,
    ) -> cudaError_t;
    pub fn ptx_tensor_graph_launch(exec: cudaGraphExec_t, stream: cudaStream_t) -> cudaError_t;
}

// ============================================================================
// cuBLAS FFI (direct bindings)
// ============================================================================

pub type cublasHandle_t = *mut c_void;
pub type cublasStatus_t = c_int;

#[repr(C)]
#[derive(Debug, Copy, Clone, PartialEq, Eq)]
pub enum cublasOperation_t {
    CUBLAS_OP_N = 0,
    CUBLAS_OP_T = 1,
    CUBLAS_OP_C = 2,
}

pub const CUBLAS_STATUS_SUCCESS: cublasStatus_t = 0;
pub const CUBLAS_STATUS_NOT_INITIALIZED: cublasStatus_t = 1;
pub const CUBLAS_STATUS_ALLOC_FAILED: cublasStatus_t = 3;
pub const CUBLAS_STATUS_INVALID_VALUE: cublasStatus_t = 7;
pub const CUBLAS_STATUS_EXECUTION_FAILED: cublasStatus_t = 13;

extern "C" {
    pub fn cublasCreate_v2(handle: *mut cublasHandle_t) -> cublasStatus_t;
    pub fn cublasDestroy_v2(handle: cublasHandle_t) -> cublasStatus_t;
    pub fn cublasSetStream_v2(handle: cublasHandle_t, stream: cudaStream_t) -> cublasStatus_t;
    pub fn cublasGetStream_v2(handle: cublasHandle_t, stream: *mut cudaStream_t) -> cublasStatus_t;

    // SGEMM: C = alpha * op(A) * op(B) + beta * C
    pub fn cublasSgemm_v2(
        handle: cublasHandle_t,
        transa: cublasOperation_t,
        transb: cublasOperation_t,
        m: c_int,
        n: c_int,
        k: c_int,
        alpha: *const f32,
        A: *const f32,
        lda: c_int,
        B: *const f32,
        ldb: c_int,
        beta: *const f32,
        C: *mut f32,
        ldc: c_int,
    ) -> cublasStatus_t;

    // DGEMM: C = alpha * op(A) * op(B) + beta * C (double precision)
    pub fn cublasDgemm_v2(
        handle: cublasHandle_t,
        transa: cublasOperation_t,
        transb: cublasOperation_t,
        m: c_int,
        n: c_int,
        k: c_int,
        alpha: *const f64,
        A: *const f64,
        lda: c_int,
        B: *const f64,
        ldb: c_int,
        beta: *const f64,
        C: *mut f64,
        ldc: c_int,
    ) -> cublasStatus_t;

    // Strided Batched GEMM
    pub fn cublasSgemmStridedBatched(
        handle: cublasHandle_t,
        transa: cublasOperation_t,
        transb: cublasOperation_t,
        m: c_int,
        n: c_int,
        k: c_int,
        alpha: *const f32,
        A: *const f32,
        lda: c_int,
        strideA: i64,
        B: *const f32,
        ldb: c_int,
        strideB: i64,
        beta: *const f32,
        C: *mut f32,
        ldc: c_int,
        strideC: i64,
        batchCount: c_int,
    ) -> cublasStatus_t;

    // Half precision GEMM
    pub fn cublasHgemm(
        handle: cublasHandle_t,
        transa: cublasOperation_t,
        transb: cublasOperation_t,
        m: c_int,
        n: c_int,
        k: c_int,
        alpha: *const __half,
        A: *const __half,
        lda: c_int,
        B: *const __half,
        ldb: c_int,
        beta: *const __half,
        C: *mut __half,
        ldc: c_int,
    ) -> cublasStatus_t;

    // GemmEx for mixed precision
    pub fn cublasGemmEx(
        handle: cublasHandle_t,
        transa: cublasOperation_t,
        transb: cublasOperation_t,
        m: c_int,
        n: c_int,
        k: c_int,
        alpha: *const c_void,
        A: *const c_void,
        Atype: c_int,
        lda: c_int,
        B: *const c_void,
        Btype: c_int,
        ldb: c_int,
        beta: *const c_void,
        C: *mut c_void,
        Ctype: c_int,
        ldc: c_int,
        computeType: c_int,
        algo: c_int,
    ) -> cublasStatus_t;
}

// cuBLAS data types for GemmEx
pub const CUDA_R_16F: c_int = 2;
pub const CUDA_R_32F: c_int = 0;
pub const CUDA_R_64F: c_int = 1;
pub const CUDA_R_16BF: c_int = 14;

pub const CUBLAS_GEMM_DEFAULT: c_int = -1;
pub const CUBLAS_GEMM_DEFAULT_TENSOR_OP: c_int = 99;

// ============================================================================
// CUDA Runtime FFI (minimal set needed)
// ============================================================================

pub const CUDA_SUCCESS: cudaError_t = 0;

extern "C" {
    pub fn cudaStreamSynchronize(stream: cudaStream_t) -> cudaError_t;
    pub fn cudaDeviceSynchronize() -> cudaError_t;
    pub fn cudaGetLastError() -> cudaError_t;
    pub fn cudaGetErrorString(error: cudaError_t) -> *const c_char;
    pub fn cudaMemcpy(
        dst: *mut c_void,
        src: *const c_void,
        count: size_t,
        kind: c_int,
    ) -> cudaError_t;
    pub fn cudaMemcpyAsync(
        dst: *mut c_void,
        src: *const c_void,
        count: size_t,
        kind: c_int,
        stream: cudaStream_t,
    ) -> cudaError_t;
    pub fn cudaMemset(devPtr: *mut c_void, value: c_int, count: size_t) -> cudaError_t;
    pub fn cudaMemsetAsync(
        devPtr: *mut c_void,
        value: c_int,
        count: size_t,
        stream: cudaStream_t,
    ) -> cudaError_t;

    // Standard CUDA allocation functions (for benchmarking comparison)
    pub fn cudaMalloc(devPtr: *mut *mut c_void, size: size_t) -> cudaError_t;
    pub fn cudaFree(devPtr: *mut c_void) -> cudaError_t;
    pub fn cudaStreamCreate(pStream: *mut cudaStream_t) -> cudaError_t;
    pub fn cudaStreamDestroy(stream: cudaStream_t) -> cudaError_t;

    // CUDA-OpenGL interop (for zero-copy graphics visualization).
    pub fn cudaGraphicsGLRegisterBuffer(
        resource: *mut cudaGraphicsResource_t,
        buffer: u32,
        flags: u32,
    ) -> cudaError_t;
    pub fn cudaGraphicsUnregisterResource(resource: cudaGraphicsResource_t) -> cudaError_t;
    pub fn cudaGraphicsMapResources(
        count: c_int,
        resources: *mut cudaGraphicsResource_t,
        stream: cudaStream_t,
    ) -> cudaError_t;
    pub fn cudaGraphicsUnmapResources(
        count: c_int,
        resources: *mut cudaGraphicsResource_t,
        stream: cudaStream_t,
    ) -> cudaError_t;
    pub fn cudaGraphicsResourceGetMappedPointer(
        devPtr: *mut *mut c_void,
        size: *mut size_t,
        resource: cudaGraphicsResource_t,
    ) -> cudaError_t;

    // CUDA IPC for cross-process device memory sharing.
    pub fn cudaIpcGetMemHandle(
        handle: *mut cudaIpcMemHandle_t,
        devPtr: *mut c_void,
    ) -> cudaError_t;
    pub fn cudaIpcOpenMemHandle(
        devPtr: *mut *mut c_void,
        handle: cudaIpcMemHandle_t,
        flags: c_uint,
    ) -> cudaError_t;
    pub fn cudaIpcCloseMemHandle(devPtr: *mut c_void) -> cudaError_t;
}

// cudaError_t constants
pub const cudaSuccess: cudaError_t = 0;
pub const cudaErrorInvalidValue: cudaError_t = 1;
pub const cudaErrorMemoryAllocation: cudaError_t = 2;

// cudaMemcpyKind
pub const cudaMemcpyHostToHost: c_int = 0;
pub const cudaMemcpyHostToDevice: c_int = 1;
pub const cudaMemcpyDeviceToHost: c_int = 2;
pub const cudaMemcpyDeviceToDevice: c_int = 3;
pub const cudaMemcpyDefault: c_int = 4;

// cudaGraphicsRegisterFlags
pub const cudaGraphicsRegisterFlagsNone: u32 = 0;
pub const cudaGraphicsRegisterFlagsReadOnly: u32 = 1;
pub const cudaGraphicsRegisterFlagsWriteDiscard: u32 = 2;

// cudaIpcMem flags
pub const cudaIpcMemLazyEnablePeerAccess: c_uint = 1;

// ============================================================================
// PyTorch Allocator Bridge (experimental)
// ============================================================================

/// Statistics from PTX-Torch allocator
#[repr(C)]
#[derive(Debug, Copy, Clone, Default)]
pub struct PTXTorchAllocatorStats {
    pub allocated_bytes: size_t,
    pub reserved_bytes: size_t,
    pub active_allocations: size_t,
    pub peak_allocated_bytes: size_t,
}

extern "C" {
    /// Initialize PyTorch to use PTX-OS allocator
    /// Must be called BEFORE any PyTorch operations
    /// Returns 0 on success, -1 on failure
    pub fn ptx_torch_init_allocator(device_id: c_int) -> c_int;

    /// Cleanup and restore default PyTorch allocator
    pub fn ptx_torch_cleanup_allocator();

    /// Check if PTX allocator is active
    pub fn ptx_torch_is_active() -> bool;

    /// Get statistics from PTX allocator
    pub fn ptx_torch_get_stats(stats: *mut PTXTorchAllocatorStats);

    /// Map PyTorch stream to PTX-OS stream ID
    pub fn ptx_torch_set_stream_mapping(torch_stream: *mut c_void, ptx_stream_id: c_int);
}

// ============================================================================
// Multi-GPU Support
// ============================================================================

/// Maximum GPUs in a multi-GPU cluster.
pub const GPU_HOT_MAX_GPUS: usize = 16;

/// GPU interconnect type.
#[repr(C)]
#[derive(Debug, Copy, Clone, PartialEq, Eq)]
pub enum GPUCommType {
    PCIe = 0,
    NVLink = 1,
    NVSwitch = 2,
}

/// Data type for distributed tensors.
#[repr(C)]
#[derive(Debug, Copy, Clone, PartialEq, Eq)]
pub enum MultiTensorDtype {
    Float32 = 0,
    Float16 = 1,
    BFloat16 = 2,
    Int32 = 3,
    Int16 = 4,
    Int8 = 5,
    Uint8 = 6,
}

/// Opaque multi-GPU cluster handle (owned by C runtime).
#[repr(C)]
pub struct GPUMultiCluster {
    _private: [u8; 0],
}

/// Opaque distributed tensor handle (owned by C runtime).
#[repr(C)]
pub struct DistributedTensor {
    _private: [u8; 0],
}

/// Per-GPU shard of a distributed tensor.
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct TensorShard {
    pub device_id: c_int,
    pub data: *mut c_void,
    pub elements: size_t,
    pub offset: size_t,
    pub ipc_handle: cudaIpcMemHandle_t,
}

/// Aggregate statistics for a multi-GPU cluster.
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct GPUMultiStats {
    pub utilization: [f32; GPU_HOT_MAX_GPUS],
    pub memory_usage: [f32; GPU_HOT_MAX_GPUS],
    pub p2p_bandwidth: [[f32; GPU_HOT_MAX_GPUS]; GPU_HOT_MAX_GPUS],
}

impl Default for GPUMultiStats {
    fn default() -> Self {
        Self {
            utilization: [0.0; GPU_HOT_MAX_GPUS],
            memory_usage: [0.0; GPU_HOT_MAX_GPUS],
            p2p_bandwidth: [[0.0; GPU_HOT_MAX_GPUS]; GPU_HOT_MAX_GPUS],
        }
    }
}

extern "C" {
    // ---- Device Enumeration ----

    /// Measure P2P bandwidth between two devices (GB/s).
    pub fn gpu_measure_bandwidth(src_device: c_int, dst_device: c_int) -> f32;

    // ---- P2P Communication ----

    /// Enable peer-to-peer access between two GPUs (bidirectional).
    pub fn gpu_enable_p2p(src_device: c_int, dst_device: c_int) -> c_int;

    /// Disable peer-to-peer access between two GPUs.
    pub fn gpu_disable_p2p(src_device: c_int, dst_device: c_int) -> c_int;

    // ---- Cluster Management ----

    /// Initialize a multi-GPU cluster with the given device IDs.
    /// Returns NULL on failure. Each device gets its own GPUHotRuntime.
    pub fn gpu_multicluster_init(
        device_ids: *const c_int,
        num_devices: c_int,
    ) -> *mut GPUMultiCluster;

    /// Shut down a multi-GPU cluster and free all resources.
    pub fn gpu_multicluster_shutdown(cluster: *mut GPUMultiCluster);

    /// Get aggregate statistics for the cluster.
    pub fn gpu_multicluster_get_stats(
        cluster: *mut GPUMultiCluster,
        stats: *mut GPUMultiStats,
    );

    // ---- Distributed Tensor ----

    /// Create a distributed tensor sharded across cluster devices.
    /// `device_distribution` may be NULL for automatic round-robin.
    pub fn gpu_distributed_tensor_create(
        cluster: *mut GPUMultiCluster,
        name: *const c_char,
        shape: *const c_int,
        dims: c_int,
        dtype: MultiTensorDtype,
        device_distribution: *const c_int,
    ) -> *mut DistributedTensor;

    /// Free a distributed tensor and all its shards.
    pub fn gpu_distributed_tensor_free(tensor: *mut DistributedTensor);

    // ---- Data Movement ----

    /// Migrate tensor data between devices via P2P copy.
    pub fn gpu_tensor_migrate(
        tensor: *mut DistributedTensor,
        src_device: c_int,
        dst_device: c_int,
        offset: size_t,
        size: size_t,
    ) -> c_int;

    /// Broadcast tensor from one device to all others.
    pub fn gpu_broadcast_tensor(
        tensor: *mut DistributedTensor,
        src_device: c_int,
    ) -> c_int;

    /// Reduce tensor shards to a root device.
    /// `operation`: "sum", "max", "min", or "avg".
    pub fn gpu_reduce_tensor(
        result: *mut DistributedTensor,
        input: *mut DistributedTensor,
        root_device: c_int,
        operation: *const c_char,
    ) -> c_int;

    // ---- Distributed Kernel Launch ----

    /// Launch a kernel across multiple devices in the cluster.
    pub fn gpu_launch_distributed_kernel(
        cluster: *mut GPUMultiCluster,
        kernel_name: *const c_char,
        args: *const *const c_void,
        grid: dim3,
        block: dim3,
        shared_mem: size_t,
        stream: cudaStream_t,
        device_distribution: *const c_int,
    ) -> cudaError_t;

    // ---- Load Balancing ----

    /// Distribute `total_work` across devices proportional to `device_capacities`.
    pub fn gpu_balance_workload(
        cluster: *mut GPUMultiCluster,
        workload_per_device: *mut c_int,
        total_work: c_int,
        device_capacities: *const c_int,
    ) -> c_int;

    // ========================================================================
    // Graphics Kernels — GPU Software Rasterization
    // ========================================================================

    // Framebuffer operations
    pub fn ptx_gfx_clear_color(
        color_buf: *mut f32,
        r: f32, g: f32, b: f32, a: f32,
        num_pixels: u32,
        stream: cudaStream_t,
    );

    pub fn ptx_gfx_clear_depth(
        depth_buf: *mut f32,
        value: f32,
        num_pixels: u32,
        stream: cudaStream_t,
    );

    // Vertex processing
    pub fn ptx_gfx_vertex_transform(
        positions_in: *const f32,
        positions_out: *mut f32,
        mvp: *const f32,
        num_vertices: u32,
        stream: cudaStream_t,
    );

    pub fn ptx_gfx_viewport_transform(
        clip_positions: *const f32,
        screen_out: *mut f32,
        viewport_width: u32,
        viewport_height: u32,
        num_vertices: u32,
        stream: cudaStream_t,
    );

    // Triangle rasterization
    pub fn ptx_gfx_rasterize_triangles(
        screen_positions: *const f32,
        vertex_colors: *const f32,
        indices: *const u32,
        color_buf: *mut f32,
        depth_buf: *mut u32,
        fb_width: u32,
        fb_height: u32,
        num_triangles: u32,
        stream: cudaStream_t,
    );

    pub fn ptx_gfx_rasterize_normals(
        screen_positions: *const f32,
        vertex_normals: *const f32,
        indices: *const u32,
        normal_buf: *mut f32,
        depth_buf: *const u32,
        fb_width: u32,
        fb_height: u32,
        num_triangles: u32,
        stream: cudaStream_t,
    );

    // Shading
    pub fn ptx_gfx_shade_phong(
        normal_buf: *const f32,
        color_buf: *mut f32,
        depth_buf: *const u32,
        light_dir: *const f32,
        light_color: *const f32,
        ambient: *const f32,
        num_pixels: u32,
        stream: cudaStream_t,
    );

    // Framebuffer conversion
    pub fn ptx_gfx_framebuffer_to_rgba(
        color_buf: *const f32,
        rgba_out: *mut u32,
        num_pixels: u32,
        stream: cudaStream_t,
    );
}

// ============================================================================

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_dtype_sizes() {
        assert_eq!(PTXDType::F32.size_bytes(), 4);
        assert_eq!(PTXDType::F64.size_bytes(), 8);
        assert_eq!(PTXDType::F16.size_bytes(), 2);
        assert_eq!(PTXDType::I8.size_bytes(), 1);
    }

    #[test]
    fn test_config_default() {
        let config = GPUHotConfig::default();
        // pool_fraction is now 1.0 (100%) by default
        assert!((config.pool_fraction - 1.0).abs() < 0.001);
    }
}
